//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOFClientProxy.hiscentral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", ConfigurationName="hiscentral.hiscentralSoap")]
    public interface hiscentralSoap {
        
        // CODEGEN: Parameter 'GetSitesInBox2Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSitesInBox2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetSitesInBox2Response GetSitesInBox2(WOFClientProxy.hiscentral.GetSitesInBox2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSitesInBox2", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSitesInBox2Response> GetSitesInBox2Async(WOFClientProxy.hiscentral.GetSitesInBox2Request request);
        
        // CODEGEN: Parameter 'GetSitesInBoxResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSitesInBox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetSitesInBoxResponse GetSitesInBox(WOFClientProxy.hiscentral.GetSitesInBoxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSitesInBox", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSitesInBoxResponse> GetSitesInBoxAsync(WOFClientProxy.hiscentral.GetSitesInBoxRequest request);
        
        // CODEGEN: Parameter 'GetMappedVariables2Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetMappedVariables2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetMappedVariables2Response GetMappedVariables2(WOFClientProxy.hiscentral.GetMappedVariables2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetMappedVariables2", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetMappedVariables2Response> GetMappedVariables2Async(WOFClientProxy.hiscentral.GetMappedVariables2Request request);
        
        // CODEGEN: Parameter 'GetMappedVariablesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetMappedVariables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetMappedVariablesResponse GetMappedVariables(WOFClientProxy.hiscentral.GetMappedVariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetMappedVariables", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetMappedVariablesResponse> GetMappedVariablesAsync(WOFClientProxy.hiscentral.GetMappedVariablesRequest request);
        
        // CODEGEN: Parameter 'GetServicesInBoxResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetServicesInBox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetServicesInBoxResponse GetServicesInBox(WOFClientProxy.hiscentral.GetServicesInBoxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetServicesInBox", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetServicesInBoxResponse> GetServicesInBoxAsync(WOFClientProxy.hiscentral.GetServicesInBoxRequest request);
        
        // CODEGEN: Parameter 'GetServicesInBox2Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetServicesInBox2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetServicesInBox2Response GetServicesInBox2(WOFClientProxy.hiscentral.GetServicesInBox2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetServicesInBox2", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetServicesInBox2Response> GetServicesInBox2Async(WOFClientProxy.hiscentral.GetServicesInBox2Request request);
        
        // CODEGEN: Parameter 'GetWaterOneFlowServiceInfoResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetWaterOneFlowServiceInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoResponse GetWaterOneFlowServiceInfo(WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetWaterOneFlowServiceInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoResponse> GetWaterOneFlowServiceInfoAsync(WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest request);
        
        // CODEGEN: Parameter 'GetSeriesCatalogForBoxResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSeriesCatalogForBox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetSeriesCatalogForBoxResponse GetSeriesCatalogForBox(WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSeriesCatalogForBox", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSeriesCatalogForBoxResponse> GetSeriesCatalogForBoxAsync(WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest request);
        
        // CODEGEN: Parameter 'GetSeriesCatalogForBox2Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSeriesCatalogForBox2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Response GetSeriesCatalogForBox2(WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSeriesCatalogForBox2", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Response> GetSeriesCatalogForBox2Async(WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request request);
        
        // CODEGEN: Parameter 'getSeriesCatalogInBoxPagedResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/getSeriesCatalogInBoxPaged", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedResponse getSeriesCatalogInBoxPaged(WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/getSeriesCatalogInBoxPaged", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedResponse> getSeriesCatalogInBoxPagedAsync(WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest request);
        
        // CODEGEN: Parameter 'getSearchablePathsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/getSearchablePaths", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.getSearchablePathsResponse getSearchablePaths(WOFClientProxy.hiscentral.getSearchablePathsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/getSearchablePaths", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.getSearchablePathsResponse> getSearchablePathsAsync(WOFClientProxy.hiscentral.getSearchablePathsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSearchableConcepts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSearchableConcepts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetSearchableConcepts", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetSearchableConceptsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/getOntologyTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOFClientProxy.hiscentral.OntologyNode getOntologyTree(string conceptKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/getOntologyTree", ReplyAction="*")]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.OntologyNode> getOntologyTreeAsync(string conceptKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetWordList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetWordList(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hiscentral.cuahsi.org/20100205/GetWordList", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetWordListAsync(string prefixText, int count);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class Site : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string siteNameField;
        
        private string siteCodeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string hUCField;
        
        private int hUCnumericField;
        
        private string servCodeField;
        
        private string servURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SiteCode {
            get {
                return this.siteCodeField;
            }
            set {
                this.siteCodeField = value;
                this.RaisePropertyChanged("SiteCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HUC {
            get {
                return this.hUCField;
            }
            set {
                this.hUCField = value;
                this.RaisePropertyChanged("HUC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int HUCnumeric {
            get {
                return this.hUCnumericField;
            }
            set {
                this.hUCnumericField = value;
                this.RaisePropertyChanged("HUCnumeric");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string servCode {
            get {
                return this.servCodeField;
            }
            set {
                this.servCodeField = value;
                this.RaisePropertyChanged("servCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string servURL {
            get {
                return this.servURLField;
            }
            set {
                this.servURLField = value;
                this.RaisePropertyChanged("servURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class OntologyNode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keywordField;
        
        private int conceptidField;
        
        private OntologyNode[] childNodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
                this.RaisePropertyChanged("keyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int conceptid {
            get {
                return this.conceptidField;
            }
            set {
                this.conceptidField = value;
                this.RaisePropertyChanged("conceptid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OntologyNode[] childNodes {
            get {
                return this.childNodesField;
            }
            set {
                this.childNodesField = value;
                this.RaisePropertyChanged("childNodes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class OntologyPath : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conceptIDField;
        
        private string searchableKeywordField;
        
        private string conceptNameField;
        
        private string conceptPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string conceptID {
            get {
                return this.conceptIDField;
            }
            set {
                this.conceptIDField = value;
                this.RaisePropertyChanged("conceptID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchableKeyword {
            get {
                return this.searchableKeywordField;
            }
            set {
                this.searchableKeywordField = value;
                this.RaisePropertyChanged("SearchableKeyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ConceptName {
            get {
                return this.conceptNameField;
            }
            set {
                this.conceptNameField = value;
                this.RaisePropertyChanged("ConceptName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ConceptPath {
            get {
                return this.conceptPathField;
            }
            set {
                this.conceptPathField = value;
                this.RaisePropertyChanged("ConceptPath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class SeriesRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string servCodeField;
        
        private string servURLField;
        
        private string locationField;
        
        private string varCodeField;
        
        private string varNameField;
        
        private string beginDateField;
        
        private string endDateField;
        
        private string authtokenField;
        
        private int valueCountField;
        
        private string sitenameField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string datatypeField;
        
        private string valuetypeField;
        
        private string samplemediumField;
        
        private string timeunitsField;
        
        private string conceptKeywordField;
        
        private string genCategoryField;
        
        private string timeSupportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServCode {
            get {
                return this.servCodeField;
            }
            set {
                this.servCodeField = value;
                this.RaisePropertyChanged("ServCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServURL {
            get {
                return this.servURLField;
            }
            set {
                this.servURLField = value;
                this.RaisePropertyChanged("ServURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VarCode {
            get {
                return this.varCodeField;
            }
            set {
                this.varCodeField = value;
                this.RaisePropertyChanged("VarCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VarName {
            get {
                return this.varNameField;
            }
            set {
                this.varNameField = value;
                this.RaisePropertyChanged("VarName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
                this.RaisePropertyChanged("beginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string authtoken {
            get {
                return this.authtokenField;
            }
            set {
                this.authtokenField = value;
                this.RaisePropertyChanged("authtoken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ValueCount {
            get {
                return this.valueCountField;
            }
            set {
                this.valueCountField = value;
                this.RaisePropertyChanged("ValueCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sitename {
            get {
                return this.sitenameField;
            }
            set {
                this.sitenameField = value;
                this.RaisePropertyChanged("Sitename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
                this.RaisePropertyChanged("datatype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string valuetype {
            get {
                return this.valuetypeField;
            }
            set {
                this.valuetypeField = value;
                this.RaisePropertyChanged("valuetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string samplemedium {
            get {
                return this.samplemediumField;
            }
            set {
                this.samplemediumField = value;
                this.RaisePropertyChanged("samplemedium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string timeunits {
            get {
                return this.timeunitsField;
            }
            set {
                this.timeunitsField = value;
                this.RaisePropertyChanged("timeunits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string conceptKeyword {
            get {
                return this.conceptKeywordField;
            }
            set {
                this.conceptKeywordField = value;
                this.RaisePropertyChanged("conceptKeyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string genCategory {
            get {
                return this.genCategoryField;
            }
            set {
                this.genCategoryField = value;
                this.RaisePropertyChanged("genCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string TimeSupport {
            get {
                return this.timeSupportField;
            }
            set {
                this.timeSupportField = value;
                this.RaisePropertyChanged("TimeSupport");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class ServiceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string servURLField;
        
        private string titleField;
        
        private string serviceDescriptionURLField;
        
        private string nameField;
        
        private string emailField;
        
        private string phoneField;
        
        private string organizationField;
        
        private string orgwebsiteField;
        
        private string citationField;
        
        private string aabstractField;
        
        private int valuecountField;
        
        private int variablecountField;
        
        private int sitecountField;
        
        private int serviceIDField;
        
        private string networkNameField;
        
        private double minxField;
        
        private double minyField;
        
        private double maxxField;
        
        private double maxyField;
        
        private string serviceStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string servURL {
            get {
                return this.servURLField;
            }
            set {
                this.servURLField = value;
                this.RaisePropertyChanged("servURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceDescriptionURL {
            get {
                return this.serviceDescriptionURLField;
            }
            set {
                this.serviceDescriptionURLField = value;
                this.RaisePropertyChanged("ServiceDescriptionURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
                this.RaisePropertyChanged("organization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string orgwebsite {
            get {
                return this.orgwebsiteField;
            }
            set {
                this.orgwebsiteField = value;
                this.RaisePropertyChanged("orgwebsite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string citation {
            get {
                return this.citationField;
            }
            set {
                this.citationField = value;
                this.RaisePropertyChanged("citation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string aabstract {
            get {
                return this.aabstractField;
            }
            set {
                this.aabstractField = value;
                this.RaisePropertyChanged("aabstract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int valuecount {
            get {
                return this.valuecountField;
            }
            set {
                this.valuecountField = value;
                this.RaisePropertyChanged("valuecount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int variablecount {
            get {
                return this.variablecountField;
            }
            set {
                this.variablecountField = value;
                this.RaisePropertyChanged("variablecount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int sitecount {
            get {
                return this.sitecountField;
            }
            set {
                this.sitecountField = value;
                this.RaisePropertyChanged("sitecount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("ServiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string NetworkName {
            get {
                return this.networkNameField;
            }
            set {
                this.networkNameField = value;
                this.RaisePropertyChanged("NetworkName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double minx {
            get {
                return this.minxField;
            }
            set {
                this.minxField = value;
                this.RaisePropertyChanged("minx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double miny {
            get {
                return this.minyField;
            }
            set {
                this.minyField = value;
                this.RaisePropertyChanged("miny");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double maxx {
            get {
                return this.maxxField;
            }
            set {
                this.maxxField = value;
                this.RaisePropertyChanged("maxx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double maxy {
            get {
                return this.maxyField;
            }
            set {
                this.maxyField = value;
                this.RaisePropertyChanged("maxy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string serviceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
                this.RaisePropertyChanged("serviceStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class MappedVariable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string variableNameField;
        
        private string variableCodeField;
        
        private string servCodeField;
        
        private string wSDLField;
        
        private string conceptKeywordField;
        
        private string conceptCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string variableName {
            get {
                return this.variableNameField;
            }
            set {
                this.variableNameField = value;
                this.RaisePropertyChanged("variableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string variableCode {
            get {
                return this.variableCodeField;
            }
            set {
                this.variableCodeField = value;
                this.RaisePropertyChanged("variableCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string servCode {
            get {
                return this.servCodeField;
            }
            set {
                this.servCodeField = value;
                this.RaisePropertyChanged("servCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string WSDL {
            get {
                return this.wSDLField;
            }
            set {
                this.wSDLField = value;
                this.RaisePropertyChanged("WSDL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string conceptKeyword {
            get {
                return this.conceptKeywordField;
            }
            set {
                this.conceptKeywordField = value;
                this.RaisePropertyChanged("conceptKeyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string conceptCode {
            get {
                return this.conceptCodeField;
            }
            set {
                this.conceptCodeField = value;
                this.RaisePropertyChanged("conceptCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class Box : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double xminField;
        
        private double xmaxField;
        
        private double yminField;
        
        private double ymaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double xmin {
            get {
                return this.xminField;
            }
            set {
                this.xminField = value;
                this.RaisePropertyChanged("xmin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double xmax {
            get {
                return this.xmaxField;
            }
            set {
                this.xmaxField = value;
                this.RaisePropertyChanged("xmax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double ymin {
            get {
                return this.yminField;
            }
            set {
                this.yminField = value;
                this.RaisePropertyChanged("ymin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double ymax {
            get {
                return this.ymaxField;
            }
            set {
                this.ymaxField = value;
                this.RaisePropertyChanged("ymax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSitesInBox2", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSitesInBox2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public double xmin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public double xmax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=2)]
        public double ymin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=3)]
        public double ymax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=4)]
        public string conceptKeyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=5)]
        public string networkIDs;
        
        public GetSitesInBox2Request() {
        }
        
        public GetSitesInBox2Request(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs) {
            this.xmin = xmin;
            this.xmax = xmax;
            this.ymin = ymin;
            this.ymax = ymax;
            this.conceptKeyword = conceptKeyword;
            this.networkIDs = networkIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSitesInBox2Response", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSitesInBox2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.Site[] GetSitesInBox2Result;
        
        public GetSitesInBox2Response() {
        }
        
        public GetSitesInBox2Response(WOFClientProxy.hiscentral.Site[] GetSitesInBox2Result) {
            this.GetSitesInBox2Result = GetSitesInBox2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSitesInBox", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSitesInBoxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public WOFClientProxy.hiscentral.Box box;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public string conceptKeyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=2)]
        public int[] networkIDs;
        
        public GetSitesInBoxRequest() {
        }
        
        public GetSitesInBoxRequest(WOFClientProxy.hiscentral.Box box, string conceptKeyword, int[] networkIDs) {
            this.box = box;
            this.conceptKeyword = conceptKeyword;
            this.networkIDs = networkIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSitesInBoxResponse", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSitesInBoxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.Site[] GetSitesInBoxResult;
        
        public GetSitesInBoxResponse() {
        }
        
        public GetSitesInBoxResponse(WOFClientProxy.hiscentral.Site[] GetSitesInBoxResult) {
            this.GetSitesInBoxResult = GetSitesInBoxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMappedVariables2", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetMappedVariables2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public string conceptids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public string Networkids;
        
        public GetMappedVariables2Request() {
        }
        
        public GetMappedVariables2Request(string conceptids, string Networkids) {
            this.conceptids = conceptids;
            this.Networkids = Networkids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMappedVariables2Response", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetMappedVariables2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.MappedVariable[] GetMappedVariables2Result;
        
        public GetMappedVariables2Response() {
        }
        
        public GetMappedVariables2Response(WOFClientProxy.hiscentral.MappedVariable[] GetMappedVariables2Result) {
            this.GetMappedVariables2Result = GetMappedVariables2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMappedVariables", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetMappedVariablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public string[] conceptids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public string[] Networkids;
        
        public GetMappedVariablesRequest() {
        }
        
        public GetMappedVariablesRequest(string[] conceptids, string[] Networkids) {
            this.conceptids = conceptids;
            this.Networkids = Networkids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMappedVariablesResponse", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetMappedVariablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.MappedVariable[] GetMappedVariablesResult;
        
        public GetMappedVariablesResponse() {
        }
        
        public GetMappedVariablesResponse(WOFClientProxy.hiscentral.MappedVariable[] GetMappedVariablesResult) {
            this.GetMappedVariablesResult = GetMappedVariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServicesInBox", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetServicesInBoxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public WOFClientProxy.hiscentral.Box box;
        
        public GetServicesInBoxRequest() {
        }
        
        public GetServicesInBoxRequest(WOFClientProxy.hiscentral.Box box) {
            this.box = box;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServicesInBoxResponse", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetServicesInBoxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.ServiceInfo[] GetServicesInBoxResult;
        
        public GetServicesInBoxResponse() {
        }
        
        public GetServicesInBoxResponse(WOFClientProxy.hiscentral.ServiceInfo[] GetServicesInBoxResult) {
            this.GetServicesInBoxResult = GetServicesInBoxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServicesInBox2", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetServicesInBox2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public double xmin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public double ymin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=2)]
        public double xmax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=3)]
        public double ymax;
        
        public GetServicesInBox2Request() {
        }
        
        public GetServicesInBox2Request(double xmin, double ymin, double xmax, double ymax) {
            this.xmin = xmin;
            this.ymin = ymin;
            this.xmax = xmax;
            this.ymax = ymax;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServicesInBox2Response", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetServicesInBox2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.ServiceInfo[] GetServicesInBox2Result;
        
        public GetServicesInBox2Response() {
        }
        
        public GetServicesInBox2Response(WOFClientProxy.hiscentral.ServiceInfo[] GetServicesInBox2Result) {
            this.GetServicesInBox2Result = GetServicesInBox2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaterOneFlowServiceInfo", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetWaterOneFlowServiceInfoRequest {
        
        public GetWaterOneFlowServiceInfoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaterOneFlowServiceInfoResponse", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetWaterOneFlowServiceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.ServiceInfo[] GetWaterOneFlowServiceInfoResult;
        
        public GetWaterOneFlowServiceInfoResponse() {
        }
        
        public GetWaterOneFlowServiceInfoResponse(WOFClientProxy.hiscentral.ServiceInfo[] GetWaterOneFlowServiceInfoResult) {
            this.GetWaterOneFlowServiceInfoResult = GetWaterOneFlowServiceInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeriesCatalogForBox", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSeriesCatalogForBoxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public WOFClientProxy.hiscentral.Box box;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public string conceptCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=2)]
        public int[] networkIDs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=3)]
        public string beginDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=4)]
        public string endDate;
        
        public GetSeriesCatalogForBoxRequest() {
        }
        
        public GetSeriesCatalogForBoxRequest(WOFClientProxy.hiscentral.Box box, string conceptCode, int[] networkIDs, string beginDate, string endDate) {
            this.box = box;
            this.conceptCode = conceptCode;
            this.networkIDs = networkIDs;
            this.beginDate = beginDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeriesCatalogForBoxResponse", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSeriesCatalogForBoxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.SeriesRecord[] GetSeriesCatalogForBoxResult;
        
        public GetSeriesCatalogForBoxResponse() {
        }
        
        public GetSeriesCatalogForBoxResponse(WOFClientProxy.hiscentral.SeriesRecord[] GetSeriesCatalogForBoxResult) {
            this.GetSeriesCatalogForBoxResult = GetSeriesCatalogForBoxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeriesCatalogForBox2", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSeriesCatalogForBox2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public double xmin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public double xmax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=2)]
        public double ymin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=3)]
        public double ymax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=4)]
        public string conceptKeyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=5)]
        public string networkIDs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=6)]
        public string beginDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=7)]
        public string endDate;
        
        public GetSeriesCatalogForBox2Request() {
        }
        
        public GetSeriesCatalogForBox2Request(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate) {
            this.xmin = xmin;
            this.xmax = xmax;
            this.ymin = ymin;
            this.ymax = ymax;
            this.conceptKeyword = conceptKeyword;
            this.networkIDs = networkIDs;
            this.beginDate = beginDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeriesCatalogForBox2Response", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class GetSeriesCatalogForBox2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.SeriesRecord[] GetSeriesCatalogForBox2Result;
        
        public GetSeriesCatalogForBox2Response() {
        }
        
        public GetSeriesCatalogForBox2Response(WOFClientProxy.hiscentral.SeriesRecord[] GetSeriesCatalogForBox2Result) {
            this.GetSeriesCatalogForBox2Result = GetSeriesCatalogForBox2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSeriesCatalogInBoxPaged", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class getSeriesCatalogInBoxPagedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        public double xmin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=1)]
        public double xmax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=2)]
        public double ymin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=3)]
        public double ymax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=4)]
        public string conceptKeyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=5)]
        public string networkIDs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=6)]
        public string beginDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=7)]
        public string endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=8)]
        public int pageno;
        
        public getSeriesCatalogInBoxPagedRequest() {
        }
        
        public getSeriesCatalogInBoxPagedRequest(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate, int pageno) {
            this.xmin = xmin;
            this.xmax = xmax;
            this.ymin = ymin;
            this.ymax = ymax;
            this.conceptKeyword = conceptKeyword;
            this.networkIDs = networkIDs;
            this.beginDate = beginDate;
            this.endDate = endDate;
            this.pageno = pageno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSeriesCatalogInBoxPagedResponse", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class getSeriesCatalogInBoxPagedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.SeriesRecord[] getSeriesCatalogInBoxPagedResult;
        
        public getSeriesCatalogInBoxPagedResponse() {
        }
        
        public getSeriesCatalogInBoxPagedResponse(WOFClientProxy.hiscentral.SeriesRecord[] getSeriesCatalogInBoxPagedResult) {
            this.getSeriesCatalogInBoxPagedResult = getSeriesCatalogInBoxPagedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSearchablePaths", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class getSearchablePathsRequest {
        
        public getSearchablePathsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSearchablePathsResponse", WrapperNamespace="http://hiscentral.cuahsi.org/20100205/", IsWrapped=true)]
    public partial class getSearchablePathsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WOFClientProxy.hiscentral.OntologyPath[] getSearchablePathsResult;
        
        public getSearchablePathsResponse() {
        }
        
        public getSearchablePathsResponse(WOFClientProxy.hiscentral.OntologyPath[] getSearchablePathsResult) {
            this.getSearchablePathsResult = getSearchablePathsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface hiscentralSoapChannel : WOFClientProxy.hiscentral.hiscentralSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class hiscentralSoapClient : System.ServiceModel.ClientBase<WOFClientProxy.hiscentral.hiscentralSoap>, WOFClientProxy.hiscentral.hiscentralSoap {
        
        public hiscentralSoapClient() {
        }
        
        public hiscentralSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public hiscentralSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hiscentralSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hiscentralSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetSitesInBox2Response WOFClientProxy.hiscentral.hiscentralSoap.GetSitesInBox2(WOFClientProxy.hiscentral.GetSitesInBox2Request request) {
            return base.Channel.GetSitesInBox2(request);
        }
        
        public WOFClientProxy.hiscentral.Site[] GetSitesInBox2(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs) {
            WOFClientProxy.hiscentral.GetSitesInBox2Request inValue = new WOFClientProxy.hiscentral.GetSitesInBox2Request();
            inValue.xmin = xmin;
            inValue.xmax = xmax;
            inValue.ymin = ymin;
            inValue.ymax = ymax;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            WOFClientProxy.hiscentral.GetSitesInBox2Response retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSitesInBox2(inValue);
            return retVal.GetSitesInBox2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSitesInBox2Response> WOFClientProxy.hiscentral.hiscentralSoap.GetSitesInBox2Async(WOFClientProxy.hiscentral.GetSitesInBox2Request request) {
            return base.Channel.GetSitesInBox2Async(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSitesInBox2Response> GetSitesInBox2Async(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs) {
            WOFClientProxy.hiscentral.GetSitesInBox2Request inValue = new WOFClientProxy.hiscentral.GetSitesInBox2Request();
            inValue.xmin = xmin;
            inValue.xmax = xmax;
            inValue.ymin = ymin;
            inValue.ymax = ymax;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSitesInBox2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetSitesInBoxResponse WOFClientProxy.hiscentral.hiscentralSoap.GetSitesInBox(WOFClientProxy.hiscentral.GetSitesInBoxRequest request) {
            return base.Channel.GetSitesInBox(request);
        }
        
        public WOFClientProxy.hiscentral.Site[] GetSitesInBox(WOFClientProxy.hiscentral.Box box, string conceptKeyword, int[] networkIDs) {
            WOFClientProxy.hiscentral.GetSitesInBoxRequest inValue = new WOFClientProxy.hiscentral.GetSitesInBoxRequest();
            inValue.box = box;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            WOFClientProxy.hiscentral.GetSitesInBoxResponse retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSitesInBox(inValue);
            return retVal.GetSitesInBoxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSitesInBoxResponse> WOFClientProxy.hiscentral.hiscentralSoap.GetSitesInBoxAsync(WOFClientProxy.hiscentral.GetSitesInBoxRequest request) {
            return base.Channel.GetSitesInBoxAsync(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSitesInBoxResponse> GetSitesInBoxAsync(WOFClientProxy.hiscentral.Box box, string conceptKeyword, int[] networkIDs) {
            WOFClientProxy.hiscentral.GetSitesInBoxRequest inValue = new WOFClientProxy.hiscentral.GetSitesInBoxRequest();
            inValue.box = box;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSitesInBoxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetMappedVariables2Response WOFClientProxy.hiscentral.hiscentralSoap.GetMappedVariables2(WOFClientProxy.hiscentral.GetMappedVariables2Request request) {
            return base.Channel.GetMappedVariables2(request);
        }
        
        public WOFClientProxy.hiscentral.MappedVariable[] GetMappedVariables2(string conceptids, string Networkids) {
            WOFClientProxy.hiscentral.GetMappedVariables2Request inValue = new WOFClientProxy.hiscentral.GetMappedVariables2Request();
            inValue.conceptids = conceptids;
            inValue.Networkids = Networkids;
            WOFClientProxy.hiscentral.GetMappedVariables2Response retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetMappedVariables2(inValue);
            return retVal.GetMappedVariables2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetMappedVariables2Response> WOFClientProxy.hiscentral.hiscentralSoap.GetMappedVariables2Async(WOFClientProxy.hiscentral.GetMappedVariables2Request request) {
            return base.Channel.GetMappedVariables2Async(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetMappedVariables2Response> GetMappedVariables2Async(string conceptids, string Networkids) {
            WOFClientProxy.hiscentral.GetMappedVariables2Request inValue = new WOFClientProxy.hiscentral.GetMappedVariables2Request();
            inValue.conceptids = conceptids;
            inValue.Networkids = Networkids;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetMappedVariables2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetMappedVariablesResponse WOFClientProxy.hiscentral.hiscentralSoap.GetMappedVariables(WOFClientProxy.hiscentral.GetMappedVariablesRequest request) {
            return base.Channel.GetMappedVariables(request);
        }
        
        public WOFClientProxy.hiscentral.MappedVariable[] GetMappedVariables(string[] conceptids, string[] Networkids) {
            WOFClientProxy.hiscentral.GetMappedVariablesRequest inValue = new WOFClientProxy.hiscentral.GetMappedVariablesRequest();
            inValue.conceptids = conceptids;
            inValue.Networkids = Networkids;
            WOFClientProxy.hiscentral.GetMappedVariablesResponse retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetMappedVariables(inValue);
            return retVal.GetMappedVariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetMappedVariablesResponse> WOFClientProxy.hiscentral.hiscentralSoap.GetMappedVariablesAsync(WOFClientProxy.hiscentral.GetMappedVariablesRequest request) {
            return base.Channel.GetMappedVariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetMappedVariablesResponse> GetMappedVariablesAsync(string[] conceptids, string[] Networkids) {
            WOFClientProxy.hiscentral.GetMappedVariablesRequest inValue = new WOFClientProxy.hiscentral.GetMappedVariablesRequest();
            inValue.conceptids = conceptids;
            inValue.Networkids = Networkids;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetMappedVariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetServicesInBoxResponse WOFClientProxy.hiscentral.hiscentralSoap.GetServicesInBox(WOFClientProxy.hiscentral.GetServicesInBoxRequest request) {
            return base.Channel.GetServicesInBox(request);
        }
        
        public WOFClientProxy.hiscentral.ServiceInfo[] GetServicesInBox(WOFClientProxy.hiscentral.Box box) {
            WOFClientProxy.hiscentral.GetServicesInBoxRequest inValue = new WOFClientProxy.hiscentral.GetServicesInBoxRequest();
            inValue.box = box;
            WOFClientProxy.hiscentral.GetServicesInBoxResponse retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetServicesInBox(inValue);
            return retVal.GetServicesInBoxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetServicesInBoxResponse> WOFClientProxy.hiscentral.hiscentralSoap.GetServicesInBoxAsync(WOFClientProxy.hiscentral.GetServicesInBoxRequest request) {
            return base.Channel.GetServicesInBoxAsync(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetServicesInBoxResponse> GetServicesInBoxAsync(WOFClientProxy.hiscentral.Box box) {
            WOFClientProxy.hiscentral.GetServicesInBoxRequest inValue = new WOFClientProxy.hiscentral.GetServicesInBoxRequest();
            inValue.box = box;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetServicesInBoxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetServicesInBox2Response WOFClientProxy.hiscentral.hiscentralSoap.GetServicesInBox2(WOFClientProxy.hiscentral.GetServicesInBox2Request request) {
            return base.Channel.GetServicesInBox2(request);
        }
        
        public WOFClientProxy.hiscentral.ServiceInfo[] GetServicesInBox2(double xmin, double ymin, double xmax, double ymax) {
            WOFClientProxy.hiscentral.GetServicesInBox2Request inValue = new WOFClientProxy.hiscentral.GetServicesInBox2Request();
            inValue.xmin = xmin;
            inValue.ymin = ymin;
            inValue.xmax = xmax;
            inValue.ymax = ymax;
            WOFClientProxy.hiscentral.GetServicesInBox2Response retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetServicesInBox2(inValue);
            return retVal.GetServicesInBox2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetServicesInBox2Response> WOFClientProxy.hiscentral.hiscentralSoap.GetServicesInBox2Async(WOFClientProxy.hiscentral.GetServicesInBox2Request request) {
            return base.Channel.GetServicesInBox2Async(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetServicesInBox2Response> GetServicesInBox2Async(double xmin, double ymin, double xmax, double ymax) {
            WOFClientProxy.hiscentral.GetServicesInBox2Request inValue = new WOFClientProxy.hiscentral.GetServicesInBox2Request();
            inValue.xmin = xmin;
            inValue.ymin = ymin;
            inValue.xmax = xmax;
            inValue.ymax = ymax;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetServicesInBox2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoResponse WOFClientProxy.hiscentral.hiscentralSoap.GetWaterOneFlowServiceInfo(WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest request) {
            return base.Channel.GetWaterOneFlowServiceInfo(request);
        }
        
        public WOFClientProxy.hiscentral.ServiceInfo[] GetWaterOneFlowServiceInfo() {
            WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest inValue = new WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest();
            WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoResponse retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetWaterOneFlowServiceInfo(inValue);
            return retVal.GetWaterOneFlowServiceInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoResponse> WOFClientProxy.hiscentral.hiscentralSoap.GetWaterOneFlowServiceInfoAsync(WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest request) {
            return base.Channel.GetWaterOneFlowServiceInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoResponse> GetWaterOneFlowServiceInfoAsync() {
            WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest inValue = new WOFClientProxy.hiscentral.GetWaterOneFlowServiceInfoRequest();
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetWaterOneFlowServiceInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetSeriesCatalogForBoxResponse WOFClientProxy.hiscentral.hiscentralSoap.GetSeriesCatalogForBox(WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest request) {
            return base.Channel.GetSeriesCatalogForBox(request);
        }
        
        public WOFClientProxy.hiscentral.SeriesRecord[] GetSeriesCatalogForBox(WOFClientProxy.hiscentral.Box box, string conceptCode, int[] networkIDs, string beginDate, string endDate) {
            WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest inValue = new WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest();
            inValue.box = box;
            inValue.conceptCode = conceptCode;
            inValue.networkIDs = networkIDs;
            inValue.beginDate = beginDate;
            inValue.endDate = endDate;
            WOFClientProxy.hiscentral.GetSeriesCatalogForBoxResponse retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSeriesCatalogForBox(inValue);
            return retVal.GetSeriesCatalogForBoxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSeriesCatalogForBoxResponse> WOFClientProxy.hiscentral.hiscentralSoap.GetSeriesCatalogForBoxAsync(WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest request) {
            return base.Channel.GetSeriesCatalogForBoxAsync(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSeriesCatalogForBoxResponse> GetSeriesCatalogForBoxAsync(WOFClientProxy.hiscentral.Box box, string conceptCode, int[] networkIDs, string beginDate, string endDate) {
            WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest inValue = new WOFClientProxy.hiscentral.GetSeriesCatalogForBoxRequest();
            inValue.box = box;
            inValue.conceptCode = conceptCode;
            inValue.networkIDs = networkIDs;
            inValue.beginDate = beginDate;
            inValue.endDate = endDate;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSeriesCatalogForBoxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Response WOFClientProxy.hiscentral.hiscentralSoap.GetSeriesCatalogForBox2(WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request request) {
            return base.Channel.GetSeriesCatalogForBox2(request);
        }
        
        public WOFClientProxy.hiscentral.SeriesRecord[] GetSeriesCatalogForBox2(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate) {
            WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request inValue = new WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request();
            inValue.xmin = xmin;
            inValue.xmax = xmax;
            inValue.ymin = ymin;
            inValue.ymax = ymax;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            inValue.beginDate = beginDate;
            inValue.endDate = endDate;
            WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Response retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSeriesCatalogForBox2(inValue);
            return retVal.GetSeriesCatalogForBox2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Response> WOFClientProxy.hiscentral.hiscentralSoap.GetSeriesCatalogForBox2Async(WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request request) {
            return base.Channel.GetSeriesCatalogForBox2Async(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Response> GetSeriesCatalogForBox2Async(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate) {
            WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request inValue = new WOFClientProxy.hiscentral.GetSeriesCatalogForBox2Request();
            inValue.xmin = xmin;
            inValue.xmax = xmax;
            inValue.ymin = ymin;
            inValue.ymax = ymax;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            inValue.beginDate = beginDate;
            inValue.endDate = endDate;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).GetSeriesCatalogForBox2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedResponse WOFClientProxy.hiscentral.hiscentralSoap.getSeriesCatalogInBoxPaged(WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest request) {
            return base.Channel.getSeriesCatalogInBoxPaged(request);
        }
        
        public WOFClientProxy.hiscentral.SeriesRecord[] getSeriesCatalogInBoxPaged(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate, int pageno) {
            WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest inValue = new WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest();
            inValue.xmin = xmin;
            inValue.xmax = xmax;
            inValue.ymin = ymin;
            inValue.ymax = ymax;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            inValue.beginDate = beginDate;
            inValue.endDate = endDate;
            inValue.pageno = pageno;
            WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedResponse retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).getSeriesCatalogInBoxPaged(inValue);
            return retVal.getSeriesCatalogInBoxPagedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedResponse> WOFClientProxy.hiscentral.hiscentralSoap.getSeriesCatalogInBoxPagedAsync(WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest request) {
            return base.Channel.getSeriesCatalogInBoxPagedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedResponse> getSeriesCatalogInBoxPagedAsync(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate, int pageno) {
            WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest inValue = new WOFClientProxy.hiscentral.getSeriesCatalogInBoxPagedRequest();
            inValue.xmin = xmin;
            inValue.xmax = xmax;
            inValue.ymin = ymin;
            inValue.ymax = ymax;
            inValue.conceptKeyword = conceptKeyword;
            inValue.networkIDs = networkIDs;
            inValue.beginDate = beginDate;
            inValue.endDate = endDate;
            inValue.pageno = pageno;
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).getSeriesCatalogInBoxPagedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOFClientProxy.hiscentral.getSearchablePathsResponse WOFClientProxy.hiscentral.hiscentralSoap.getSearchablePaths(WOFClientProxy.hiscentral.getSearchablePathsRequest request) {
            return base.Channel.getSearchablePaths(request);
        }
        
        public WOFClientProxy.hiscentral.OntologyPath[] getSearchablePaths() {
            WOFClientProxy.hiscentral.getSearchablePathsRequest inValue = new WOFClientProxy.hiscentral.getSearchablePathsRequest();
            WOFClientProxy.hiscentral.getSearchablePathsResponse retVal = ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).getSearchablePaths(inValue);
            return retVal.getSearchablePathsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WOFClientProxy.hiscentral.getSearchablePathsResponse> WOFClientProxy.hiscentral.hiscentralSoap.getSearchablePathsAsync(WOFClientProxy.hiscentral.getSearchablePathsRequest request) {
            return base.Channel.getSearchablePathsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.getSearchablePathsResponse> getSearchablePathsAsync() {
            WOFClientProxy.hiscentral.getSearchablePathsRequest inValue = new WOFClientProxy.hiscentral.getSearchablePathsRequest();
            return ((WOFClientProxy.hiscentral.hiscentralSoap)(this)).getSearchablePathsAsync(inValue);
        }
        
        public string[] GetSearchableConcepts() {
            return base.Channel.GetSearchableConcepts();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSearchableConceptsAsync() {
            return base.Channel.GetSearchableConceptsAsync();
        }
        
        public WOFClientProxy.hiscentral.OntologyNode getOntologyTree(string conceptKeyword) {
            return base.Channel.getOntologyTree(conceptKeyword);
        }
        
        public System.Threading.Tasks.Task<WOFClientProxy.hiscentral.OntologyNode> getOntologyTreeAsync(string conceptKeyword) {
            return base.Channel.getOntologyTreeAsync(conceptKeyword);
        }
        
        public string[] GetWordList(string prefixText, int count) {
            return base.Channel.GetWordList(prefixText, count);
        }
        
        public System.Threading.Tasks.Task<string[]> GetWordListAsync(string prefixText, int count) {
            return base.Channel.GetWordListAsync(prefixText, count);
        }
    }
}
